### PR TITLE
Creating initial home page for Greenwich SWC bootcamp

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by jiffyclub** [comment]
Whoa, this doesn't look right.

**Comment by jiffyclub** [comment]
Oh, I guess this is a new repo so you're bringing everything over. Was scary seeing all those commits.

**Comment by amyrhoda** [comment]
I'm not sure I understand why this is going into swcarpentry:master -- are you merging in improvements you made? Or is this a new bootcamp page? If so, doesn't it stay under gvwilson?

**Comment by gvwilson** [comment]
I thought it made sense for the master copy of the Greenwich bootcamp 
repo to be owned by the 'swcarpentry' user, so that 'gvwilson' could 
have a fork and do pull requests (rather than pushing material directly 
without any possibility of review).  What I probably _should_ do is 
squash all the history so that there isn't a pile full of commits, but 
our directions in the 'bc' repo's 'README.md' file don't tell people to 
do that, so I didn't.  (I'm also pretty sure I'd screw it up if I tried 
to do it...)

**Comment by jiffyclub** [comment]
Upon making a new repo I would push directly all of the existing bc stuff then make a PR that contains just the new commits.

**Comment by amyrhoda** [comment]
Okay, I see. I was wondering how to transfer a repo from one user to another. There's a way to just do that (transfer a repo) but this works too.

**Comment by gvwilson** [comment]
On 2013-09-09 2:58 PM, Matt Davis wrote:

> Upon making a new repo I would push directly all of the existing bc 
> stuff then make a PR that contains just the new commits.
> 
> OK, so the steps are:
1. make new repo on GitHub
2. git clone to desktop
3. add swcarpentry/bc as remote
4. git checkout -b gh-pages
5. git pull swcarpentry gh-pages
6. something something
7. git commit -m "Initializing new bootcamp repo"
8. git push origin gh-pages

What's the something something?

**Comment by jiffyclub** [comment]
That might work, I'd have to try it. I think points 6 and 7 are unnecessary.

I was thinking:
1. make new repo on GitHub
2. `cd bc`
3. add swcarpentry/new-repo as a remote
4. `git push new-repo gh-pages`
5. clone new repo and hack as usual

**Comment by jiffyclub** [comment]
Yes, but it won't show up in PRs as happened here. It'll still be there, people just won't have to think about it in order to evaluate new content on top of it.

**Pull request closed without merging**
